name: criterion
description: A statistics-driven benchmarking library for Dart, inspired by Rust's criterion.rs.
version: 1.0.0
repository: https://github.com/sigurdm/criterion
issue_tracker: https://github.com/sigurdm/criterion/issues
topics:
  - benchmark
  - benchmarking
  - performance
  - statistics
  - profiling

environment:
  sdk: ^3.12.0

# Add regular dependencies here.
dependencies:
  ffi: ^2.2.0
  vm_service: '>=14.0.0 <17.0.0'
  path: ^1.9.0
  args: ^2.5.0
  node_preamble: ^2.0.2
  hooks: ^2.2.0
  code_assets: ^2.1.0
  native_toolchain_c: ^0.19.5

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  puppeteer: ^3.0.0
executables:
  run: run
  compare: compare
  compare_git: compare_git
  graph: graph
